services:
  db:
    image: postgres:15-alpine
    container_name: swipe_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swipe
    ports:
      - "5432:5432"
    volumes:
      - swipe_new_data:/var/lib/postgresql/data

volumes:
  swipe_new_data:
